# Generated by Django 5.0.2 on 2025-07-11 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('company_name', models.CharField(max_length=100)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('specializations', models.CharField(blank=True, max_length=200)),
                ('service_areas', models.CharField(blank=True, max_length=200)),
                ('languages', models.CharField(blank=True, max_length=100)),
                ('office_phone', models.CharField(blank=True, max_length=20)),
                ('office_address', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('awards', models.TextField(blank=True)),
                ('notify_new_inquiries', models.BooleanField(default=True)),
                ('notify_property_updates', models.BooleanField(default=True)),
                ('notify_client_messages', models.BooleanField(default=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_listings', models.PositiveIntegerField(default=0)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['-created_at'],
            },
        ),
    ]
