# Generated by Django 5.0.2 on 2025-07-11 19:49

from django.db import migrations, models
import django.db.models.deletion

def set_initial_owners(apps, schema_editor):
    Property = apps.get_model('properties', 'Property')
    for property in Property.objects.all():
        if property.agent:
            property.owner = property.agent
            property.save()

class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        # First add the owner field allowing null
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='owned_properties',
                to='accounts.user',
                limit_choices_to={'role__in': ['agent', 'seller']}
            ),
        ),
        # Run the data migration
        migrations.RunPython(set_initial_owners),
        # Make the owner field required
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='owned_properties',
                to='accounts.user',
                limit_choices_to={'role__in': ['agent', 'seller']}
            ),
        ),
        # Update the agent field to allow null and be optional
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='managed_properties',
                to='accounts.user',
                limit_choices_to={'role': 'agent'}
            ),
        ),
    ]
