# Generated by Django 5.0.2 on 2025-07-11 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20250711_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='longitude',
        ),
    ]
