# Generated by Django 5.0.2 on 2025-07-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_property_latitude_remove_property_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
